In [1]:
import xml.dom.minidom 
from xml.dom.minidom import parse

In [2]:
t = parse("../data_set/Laptops_Train.xml")

In [142]:
dom = parse("../data_set/Laptops_Train.xml")
result = []
dom.hasChildNodes()
for s in dom.getElementsByTagName("sentence"):
    s_id = s.getAttribute("id")
    text = s.getElementsByTagName("text")[0].firstChild.data
    ats = s.getElementsByTagName("aspectTerm")
    terms = []
    polaritys = []
    if ats:
        for i in range(len(ats)):
            terms.append(ats[i].getAttribute("term"))
            polaritys.append(ats[i].getAttribute("polarity"))
    content = {"id":s_id, "text": text, "terms":terms, "polarity":polaritys}
    result.append(content)

In [143]:
result

[{'id': '2339',
  'text': 'I charge it at night and skip taking the cord with me because of the good battery life.',
  'terms': ['cord', 'battery life'],
  'polarity': ['neutral', 'positive']},
 {'id': '812',
  'text': 'I bought a HP Pavilion DV4-1222nr laptop and have had so many problems with the computer.',
  'terms': [],
  'polarity': []},
 {'id': '1316',
  'text': 'The tech guy then said the service center does not do 1-to-1 exchange and I have to direct my concern to the "sales" team, which is the retail shop which I bought my netbook from.',
  'terms': ['service center', '"sales" team', 'tech guy'],
  'polarity': ['negative', 'negative', 'neutral']},
 {'id': '2328',
  'text': 'I investigated netbooks and saw the Toshiba NB305-N410BL.',
  'terms': [],
  'polarity': []},
 {'id': '2193',
  'text': 'The other day I had a presentation to do for a seminar at a large conference in town- lots of people, little time to prep and have to set up a computer to a projector, etc.',
  'terms': 

In [56]:
root = t.documentElement

In [145]:
dom = parse("../data_set/restaurants-trial.xml")
result = []
for s in dom.getElementsByTagName("sentence"):
    s_id = s.getAttribute("id")
    text = s.getElementsByTagName("text")[0].firstChild.data
    ats = s.getElementsByTagName("aspectTerm")
    asc = s.getElementsByTagName("aspectCategory")
    terms = []
    term_polaritys = []
    cates = []
    cate_polaritys = []
    if ats:
        for i in range(len(ats)):
            terms.append(ats[i].getAttribute("term"))
            term_polaritys.append(ats[i].getAttribute("polarity"))
    if asc:
        for i in range(len(asc)):
            cates.append(asc[i].getAttribute("category"))
            cate_polaritys.append(asc[i].getAttribute("polarity"))
    content = {"id": s_id,"text": text,"terms": terms,"term_polarity": term_polaritys,"category":cates,
                        "category_polarity":cate_polaritys}
    result.append(content)


In [146]:
result

[{'id': '813',
  'text': 'All the appetizers and salads were fabulous, the steak was mouth watering and the pasta was delicious!!!',
  'terms': ['appetizers', 'salads', 'steak', 'pasta'],
  'term_polarity': ['positive', 'positive', 'positive', 'positive'],
  'category': ['food'],
  'category_polarity': ['positive']},
 {'id': '1579',
  'text': 'And really large portions.',
  'terms': ['portions'],
  'term_polarity': ['positive'],
  'category': ['food'],
  'category_polarity': ['positive']},
 {'id': '2707',
  'text': "Go inside and you won't want to leave.",
  'terms': [],
  'term_polarity': [],
  'category': ['anecdotes/miscellaneous'],
  'category_polarity': ['positive']},
 {'id': '3126',
  'text': 'Save yourself the time and trouble and skip this one!',
  'terms': [],
  'term_polarity': [],
  'category': ['anecdotes/miscellaneous'],
  'category_polarity': ['negative']},
 {'id': '2882',
  'text': 'The sweet lassi was excellent as was the lamb chettinad and the garlic naan but the rasam

In [57]:
root

<DOM Element: sentences at 0x1c6b349cd58>

In [103]:
a = root.getElementsByTagName("sentence")[0]

In [130]:
s1 = root.getElementsByTagName("sentence")[0:5]

In [ ]:
a.getAttribute()

In [111]:
s1[0].childNodes

[<DOM Text node "'\n        '">,
 <DOM Element: text at 0x1c6b349ce88>,
 <DOM Text node "'\n        '">,
 <DOM Element: aspectTerms at 0x1c6b349cf20>,
 <DOM Text node "'\n    '">]

In [140]:
for s in s1:
#     print(s.childNodes[1].firstChild.data)
    ats = s.getElementsByTagName("aspectTerm")
    if ats:
#         print(len(ats))
        for i in range(len(ats)):
            print(ats[i].getAttribute("term"))
#     if s.hasChildNodes() != []:
#         print(s.getElementsByTagName("aspectTerms"))
#     else:
#         pass
#     print(s.hasChildNodes("aspectTerms"))
#     print(s.childNodes[3].getElementsByTagName("aspectTerm"))

cord
battery life
service center
"sales" team
tech guy


In [84]:
s.childNodes[3].childNodes[1].get("term")

'cord'

In [73]:
s.childNodes[1].firstChild.data

'I charge it at night and skip taking the cord with me because of the good battery life.'

In [60]:
s.childNodes.

AttributeError: 'Element' object has no attribute 'getElementByTagName'

In [94]:
s.getUserData("from")

In [27]:
s1 = s.getElementsByTagName("text")

In [33]:
s1.item

AttributeError: 'Element' object has no attribute 'item'

In [148]:
import pandas as pd
import numpy as np

In [206]:
train = pd.read_csv("../data_set/laptops-train.csv")

In [207]:
train.head()

id                                               text  \
0   1                            All I can say is W-O-W.   
1   2                           This laptop is insane!!!   
2   3  It's so nice to look at and the keys are easy ...   
3   4  I bought a protector for my key pad and it wor...   
4   5     This is definitely a computer worth the money;   

                      terms             term_polarity  
0                        []                        []  
1                        []                        []  
2          ['keys', 'look']  ['positive', 'positive']  
3  ['protector', 'key pad']   ['neutral', 'positive']  
4                        []                        []

In [208]:
train.shape
trains = train[train.terms.values != "[]"]

In [209]:
trains.head()

id                                               text  \
2   3  It's so nice to look at and the keys are easy ...   
3   4  I bought a protector for my key pad and it wor...   
5   6  The mouse is a little bit different than what ...   
6   7  AND the best part is that it even comes with a...   
7   8  Overall, this laptop is definitely a keeper wi...   

                      terms             term_polarity  
2          ['keys', 'look']  ['positive', 'positive']  
3  ['protector', 'key pad']   ['neutral', 'positive']  
5                 ['mouse']              ['conflict']  
6               ['printer']              ['positive']  
7      ['design', 'colors']  ['positive', 'positive']

In [165]:
t = trains[trains.id.values == 3].copy()

In [168]:
t1 = trains[trains.id.values == 3]

In [169]:
new_t = pd.DataFrame()
for i in range(2):
    new_t = pd.concat([new_t, t1], axis=0, ignore_index=True)

In [210]:
trains["terms_len"] = trains["terms"].apply(lambda x: len(eval(x)))

D:\Anacond\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [211]:
def generate(line):
    terms = eval(line[2])
    terms_polarity = eval(line[3])
    content = {}
    result = pd.DataFrame()
    for i in range(line[4]):
        content["id"] = line[0]
        content["text"] = line[1]
        content["term"] = terms[i]
        content["term_polarity"] = terms_polarity[i]
        cpd = pd.DataFrame.from_dict(content,orient="index").T
        result = pd.concat([result, cpd])
    return result

In [212]:
new_train = pd.DataFrame()
for t in trains.values:
#     print(t)
    s = generate(t)
    new_train = pd.concat([new_train, s], axis=0, ignore_index=True)

In [213]:
new_train.head()
# new_train.shape

id                                               text       term  \
0  3  It's so nice to look at and the keys are easy ...       keys   
1  3  It's so nice to look at and the keys are easy ...       look   
2  4  I bought a protector for my key pad and it wor...  protector   
3  4  I bought a protector for my key pad and it wor...    key pad   
4  6  The mouse is a little bit different than what ...      mouse   

  term_polarity  
0      positive  
1      positive  
2       neutral  
3      positive  
4      conflict

In [216]:
new_train[["term_polarity"]].drop_duplicates()

term_polarity
0       positive
2        neutral
4       conflict
11      negative

In [219]:
new_train[new_train.term_polarity == "negative"].shape

(854, 4)

In [214]:
trains.head()

id                                               text  \
2   3  It's so nice to look at and the keys are easy ...   
3   4  I bought a protector for my key pad and it wor...   
5   6  The mouse is a little bit different than what ...   
6   7  AND the best part is that it even comes with a...   
7   8  Overall, this laptop is definitely a keeper wi...   

                      terms             term_polarity  terms_len  
2          ['keys', 'look']  ['positive', 'positive']          2  
3  ['protector', 'key pad']   ['neutral', 'positive']          2  
5                 ['mouse']              ['conflict']          1  
6               ['printer']              ['positive']          1  
7      ['design', 'colors']  ['positive', 'positive']          2

In [280]:
new_t

id                                               text             terms  \
0   3  It's so nice to look at and the keys are easy ...  ['keys', 'look']   
1   3  It's so nice to look at and the keys are easy ...  ['keys', 'look']   

              term_polarity  
0  ['positive', 'positive']  
1  ['positive', 'positive']

In [310]:
trains = pd.read_csv("../data_set/restaurants-train.csv")

In [311]:
trains = trains[trains.terms.values != "[]"]

In [312]:
trains["terms_len"] = trains["terms"].apply(lambda x: len(eval(x)))
trains = trains[["id","text","terms","term_polarity","terms_len"]]

In [314]:
trains.head()
trains.shape

(2023, 5)

In [302]:
def generate(line):
    terms = eval(line[2])
    terms_polarity = eval(line[3])
    content = {}
    result = pd.DataFrame()
    for i in range(line[4]):
        content["id"] = line[0]
        content["text"] = line[1]
        content["term"] = terms[i]
        content["term_polarity"] = terms_polarity[i]
        cpd = pd.DataFrame.from_dict(content,orient="index").T
        result = pd.concat([result, cpd])
    return result

In [303]:
new_train = pd.DataFrame()
for t in trains.values:
#     print(t)
    s = generate(t)
    new_train = pd.concat([new_train, s], axis=0, ignore_index=True)

In [304]:
new_train.head()

id                                               text         term  \
0  16  night without a reservation, we had to wait at...      manager   
1  16  night without a reservation, we had to wait at...  reservation   
2  16  night without a reservation, we had to wait at...          bar   
3  16  night without a reservation, we had to wait at...         wait   
4  83                                 Reasonable prices.       prices   

  term_polarity  
0      positive  
1       neutral  
2       neutral  
3      positive  
4      positive

In [305]:
new_train.shape

(391, 4)

In [306]:
new_train[["term_polarity"]].drop_duplicates()

term_polarity
0       positive
1        neutral
5       conflict
15      negative

In [309]:
new_train[new_train.term_polarity == "neutral"].shape

(65, 4)

In [291]:
sample = {1:[(1,2)],2:[(1,3)]}

In [296]:
s = (1,2)

In [297]:
s[0]

1

In [321]:
rarray=0.2*np.random.random((10,5))-0.1 

In [323]:
rarray[0] = [1,2,3,4,5]

In [324]:
rarray

array([[ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
         4.00000000e+00,  5.00000000e+00],
       [ 7.05961331e-02,  2.14152064e-02,  5.42152044e-02,
         8.32180856e-02, -7.52616562e-02],
       [-4.31554700e-02, -6.35287576e-02, -5.08813066e-02,
        -4.06407586e-02,  1.60741804e-02],
       [-7.81837680e-02, -8.58980237e-02,  5.12795471e-02,
        -4.33833999e-02,  5.34582780e-03],
       [-3.31336380e-02,  1.16463706e-02,  2.81712744e-02,
        -7.67927880e-02,  2.38114999e-03],
       [ 2.88960375e-03,  3.37441554e-02, -9.01869485e-02,
         4.95589961e-02,  2.51993504e-02],
       [-3.83950947e-02, -7.53020832e-02,  1.44377344e-02,
         9.18924118e-02,  1.92535518e-02],
       [-6.27850930e-03,  1.37983701e-02, -3.32820966e-02,
         1.26608441e-02, -5.29302716e-02],
       [ 3.49736108e-02,  7.49233658e-03,  1.26302828e-02,
         5.02712719e-02, -1.58588916e-02],
       [ 7.18287416e-02,  6.20318791e-02, -2.12717007e-02,
         2.25037854e-02

In [325]:
#coding=utf-8
import tensorflow as tf
import numpy as np
# 创建输入数据
X = np.random.randn(2, 10, 8)

# 第二个example长度为6
X[1,6:] = 0
X_lengths = [10, 6]

cell = tf.contrib.rnn.BasicLSTMCell(num_units=64, state_is_tuple=True)

outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)

result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.
Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.
Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.


In [344]:
result[0]["last_states"][0][1,6:8]

array([ 0.09387377, -0.0157348 ])

In [348]:
result[0]["outputs"][1,6,:]

array([ 0.04295722, -0.01338491,  0.00606821,  0.06430125,  0.05179751,
       -0.03461833,  0.05169923, -0.00851983,  0.00378394, -0.10597341,
        0.01880586,  0.08085688,  0.03045719, -0.00148532,  0.06270722,
        0.05837756, -0.06322224,  0.039059  ,  0.02370497, -0.06955833,
       -0.02266466,  0.02840846, -0.05060187, -0.10626533, -0.00699144,
       -0.03544327, -0.04961321, -0.03089647,  0.011901  ,  0.0329381 ,
       -0.0637482 , -0.05717803, -0.08275054, -0.05862856,  0.0717137 ,
        0.04317753, -0.06699531, -0.10389336,  0.00443626,  0.15822713,
        0.05843571,  0.00101034,  0.10051276, -0.0820644 ,  0.02120507,
        0.04642212,  0.00600841, -0.0144751 , -0.01845015, -0.08511297,
        0.04210438, -0.05256345,  0.00868364,  0.01137434, -0.01476934,
       -0.0487781 ,  0.01262179,  0.0678599 , -0.02471912, -0.078949  ,
       -0.00041674,  0.0117354 , -0.05310234, -0.0014039 ])

In [355]:
import torch
s = torch.Tensor([[    2,    17,     4,      0,     0,     0],
        [  267,   331,     2,       0,     0,     0],
        [  120,   494,   495,     0,     0,     0]])

In [ ]:
torch.cuda.

In [380]:
torch.cuda.LongTensor(list(map(lambda x: x[::-1],s.data.tolist())))

tensor([[   0,    0,    0,    4,   17,    2],
        [   0,    0,    0,    2,  331,  267],
        [   0,    0,    0,  495,  494,  120]], device='cuda:0')